// AUTO-GENERATED by briefcase_cork_port_mechanical.
// Source: hearthfield (substantive system-shaped pub fns).
// No LLM involved.
#![allow(unused)]
#![allow(dead_code)]
use bevy::prelude::*;
use std::collections::{HashMap, HashSet, BTreeSet, BTreeMap};
use serde::{Serialize, Deserialize};

// synthetic stubs filled in by the port-and-fix loop


// ported host bodies
/// Consume all non-wildcard ingredients.
pub fn dispense_treatment(inventory: &mut Inventory, recipe: &Recipe) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let removed = inventory.try_remove(item_id, *qty);
        if removed < *qty {
            warn!(
                "dispense_treatment: only removed {} of {} '{}'",
                removed, qty, item_id
            );
        }
    }
}



/// Refund all non-wildcard ingredients.
pub fn restock_treatment(
    inventory: &mut Inventory,
    recipe: &Recipe,
    registry: &ItemRegistry,
) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let max_stack = registry.get(item_id).map(|d| d.stack_size.get()).unwrap_or(99);
        inventory.try_add(item_id, *qty, max_stack);
    }
}


pub struct PortedPlugin;
impl Plugin for PortedPlugin {
    fn build(&self, _app: &mut App) {}
}
