// AUTO-GENERATED by briefcase_cork_port_mechanical.
// Source: hearthfield (substantive system-shaped pub fns).
// No LLM involved.
#![allow(unused)]
#![allow(dead_code)]
use bevy::prelude::*;
use std::collections::{HashMap, HashSet, BTreeSet, BTreeMap};
use serde::{Serialize, Deserialize};

// synthetic stubs filled in by the port-and-fix loop
#[derive(Default, Debug, Clone, Copy)]
pub struct OpaqueLeaf;
impl OpaqueLeaf {
    pub fn get<R: Default>(&self) -> R { R::default() }
    pub fn len(&self) -> usize { 0 }
    pub fn count(&self) -> usize { 0 }
    pub fn is_some(&self) -> bool { false }
    pub fn is_none(&self) -> bool { true }
    pub fn unwrap<R: Default>(&self) -> R { R::default() }
    pub fn unwrap_or<R>(&self, fallback: R) -> R { fallback }
}

#[derive(Default, Debug, Clone)]
pub struct OpaqueValue {
    pub stack_size: OpaqueLeaf,
}

#[derive(Resource, Component, Debug, Default, Clone)]
pub struct Inventory;

impl Inventory {
    pub fn try_add<A0, A1, A2>(&self, _a0: A0, _a1: A1, _a2: A2) -> bool { false }
    pub fn try_remove<A0, A1>(&self, _a0: A0, _a1: A1) -> u32 { 0 }
}

#[derive(Resource, Component, Debug, Default, Clone)]
pub struct ItemRegistry;

impl ItemRegistry {
    pub fn get<A0>(&self, _a0: A0) -> Option<OpaqueValue> { Some(OpaqueValue::default()) }
}

#[derive(Resource, Component, Debug, Default, Clone)]
pub struct Recipe {
    pub ingredients: Vec<(String, u32)>,
}


// ported host bodies
/// Consume all non-wildcard ingredients.
pub fn dispense_treatment(inventory: &mut Inventory, recipe: &Recipe) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let removed = inventory.try_remove(item_id, *qty);
        if removed < *qty {
            warn!(
                "dispense_treatment: only removed {} of {} '{}'",
                removed, qty, item_id
            );
        }
    }
}



/// Refund all non-wildcard ingredients.
pub fn restock_treatment(
    inventory: &mut Inventory,
    recipe: &Recipe,
    registry: &ItemRegistry,
) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let max_stack = registry.get(item_id).map(|d| d.stack_size.get()).unwrap_or(99);
        inventory.try_add(item_id, *qty, max_stack);
    }
}


pub struct PortedPlugin;
impl Plugin for PortedPlugin {
    fn build(&self, _app: &mut App) {}
}
