// AUTO-GENERATED by briefcase_cork_port_mechanical (mechanical port verb).
// Source: hearthfield (substantive system-shaped pub fns)
// Substitution map: 30 regex rewrites mapping hearthfield types -> lifeline types.
// No LLM involved. The gate command was `cargo check --package lifeline --quiet`.
#![allow(unused)]
#![allow(dead_code)]
use bevy::prelude::*;
use std::collections::{HashMap, HashSet, BTreeSet, BTreeMap};
use serde::{Serialize, Deserialize};

// ─── synthetic type stubs filled in by the port-and-fix loop ────────
#[derive(Resource, Component, Debug, Default, Clone)]
pub struct Inventory;

impl Inventory {
    pub fn try_add(&mut self, _id: &str, _q: u8, _m: u8) -> u8 { 0 }
    pub fn try_remove(&mut self, _id: &str, _q: u8) -> u8 { 0 }
}

#[derive(Debug, Default, Clone)]
pub struct ItemDef { pub name: String, pub stack_size: ItemStack }

#[derive(Debug, Default, Clone, Copy)]
pub struct ItemStack(pub u8);
impl ItemStack { pub fn get(self) -> u8 { self.0 } }

impl ItemDef { pub fn name(&self) -> &str { &self.name } }

#[derive(Resource, Component, Debug, Default, Clone)]
pub struct ItemRegistry;

impl ItemRegistry {
    pub fn get(&self, _id: &str) -> Option<&ItemDef> { None }
}

#[derive(Resource, Component, Debug, Default, Clone)]
pub struct Recipe {
    pub ingredients: Vec<(String, u8)>,
}


// ─── ported host bodies ─────────────────────────────────────────────
/// Consume all non-wildcard ingredients.
pub fn dispense_treatment(inventory: &mut Inventory, recipe: &Recipe) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let removed = inventory.try_remove(item_id, *qty);
        if removed < *qty {
            warn!(
                "dispense_treatment: only removed {} of {} '{}'",
                removed, qty, item_id
            );
        }
    }
}



/// Refund all non-wildcard ingredients.
pub fn restock_treatment(
    inventory: &mut Inventory,
    recipe: &Recipe,
    registry: &ItemRegistry,
) {
    for (item_id, qty) in &recipe.ingredients {
        if item_id == "any_fish" {
            continue;
        }
        let max_stack = registry.get(item_id).map(|d| d.stack_size.get()).unwrap_or(99);
        inventory.try_add(item_id, *qty, max_stack);
    }
}


// ─── plugin shell ───────────────────────────────────────────────────
pub struct PortedPlugin;

impl Plugin for PortedPlugin {
    fn build(&self, _app: &mut App) {
        // Systems registered would go here once their parameters
        // resolve cleanly against lifeline's resource set.
    }
}
